### PR TITLE
👷 Add Automatic Deployment to Production on PR Merge

### PR DESCRIPTION
**Pull request by toddtee**
This commit adds a GitHub Action that will automatically deploy the chat bot to the production instance of Slack when an approved PR is merged into the main branch of the repo.

### CODE REVIEW

**Review by ChrisPVella — COMMENTED** [review]
@toddtee is there a 'master' branch? I believe 'main' is the now promoted nomenclature.

**Comment by toddtee** [comment]
Nice pickup @ChrisPVella... I am still not used to being woke.

**Comment by toddtee** [comment]
@ChrisPVella Updated 👍

**Review by ChrisPVella — APPROVED** [review]
Looks good.

**Pull request merged**
