### PR TITLE
🐛 Ignore Old AppMentions Events

### LINKED ISSUE #16: Sugarcity-bot asks "where...", whenever a post is edited.
Whenever a post is edited, it triggers the sugarcity bot to ask "where about's in mackay would best suit".

Expected behaviour would be a single question following the original post.

image

### PR DESCRIPTION
**Pull request by toddtee**
This commit adds a check to the AppMention event handler, to check how recent the message was created. If the message is greater than 2 seconds old, it will be ignored. This will prevent the bot responding to edited, older messages.

Previously, the bot would respond to any incoming AppMention event, regardless of how old the message was.

Fixes #16.

### CODE REVIEW

**Comment by toddtee** [comment]
Yeah this sucks, but welcome to the Slack API! 🎉 

I tried checking something along the lines of a `IsEdited` parameter for the event, however this did not appear possible as we trigger this on an `AppMention` event, so this is not a parameter they attach to this type of event (they do for generic `MessageEvents`). 

So dirty time hacks it is!

**Review by Eunoseer — APPROVED** [review]
It's a shame that the slackEvents go package doesn't seem to support the concept of "message_changed". It looks like the "AppMentionEvent" struct holds the "message" data from the event. There appears to be an open issue against the slack-go library which if resolved could give us the data we need?

Note the "edited" data in the example payload.
[Slack-Go issue #961](https://github.com/slack-go/slack/issues/961)

[Slack Event API - message_changed](https://api.slack.com/events/message/message_changed)

[Slack Go - inner_events.go AppMentionEvent](https://github.com/slack-go/slack/blob/4c00dbda0cd36b3ecb9d64ed6adc79d1cb4c0ca5/slackevents/inner_events.go#L16)

**Review by dHeinemann — APPROVED** [review]
I haven't tested, but the code looks good to me. Thanks for the PR!

**Review by rickwillcox — APPROVED** [review]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Pull request merged**
